services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 2s
      retries: 12

  app:
    build: .
    container_name: mvp0-app
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: "http://127.0.0.1:8000"

      DB_CONNECTION: mongodb
      MONGODB_DATABASE: appdb
      MONGODB_URI: "mongodb://mongo:27017/appdb?directConnection=true&serverSelectionTimeoutMS=1200&retryWrites=false"

      L5_SWAGGER_GENERATE_ALWAYS: "false"

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mvp0-mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"

volumes:
  mongo-data: